version: '3'

services:
  sample:
    container_name: sample
    build:
      context: .
      dockerfile: ../source_fe/Dockerfile
    volumes:
      - '.:/app/frontend'
      - '/app/frontend/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
